name: Update GitHub Activity

on:
  schedule:
    - cron: '0 * * * *' # Roda a cada hora
  workflow_dispatch: # Permite rodar manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest # Corrigido de 'runs-activity' para 'runs-on'
    permissions:
      contents: write # Garante que a Action pode salvar as alterações no README
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Update GitHub Activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
